---

- name: Create directories
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    mode: '0700'
    group: postgres
    owner: postgres
    recurse: false
  loop:
    - { path: '{{ data_filesystem_path }}' }
    - { path: '{{ log_filesystem_path }}' }
    - { path: '{{ wal_filesystem_path }}' }

...
