---

- name: Create logical volumes with all space in volume groups
  community.general.lvol:
    active: true
    vg: '{{ item.vg }}'
    lv: '{{ item.lv }}'
    size: 100%FREE
    force: false
    resizefs: false
    shrink: false
    state: present
  loop:
    - { vg: '{{ lvm_data_volume_group }}', lv: '{{ lvm_data_logical_volume }}' }
    - { vg: '{{ lvm_log_volume_group }}', lv: '{{ lvm_log_logical_volume }}' }
    - { vg: '{{ lvm_wal_volume_group }}', lv: '{{ lvm_wal_logical_volume }}' }

...
