- name: Create PostgreSQL user
  ansible.builtin.user:
    comment: PostgreSQL user
    create_home: false
    group: postgres
    name: postgres
    shell: /bin/bash

- name: Create PostgreSQL data directory
  ansible.builtin.file:
    group: postgres
    mode: '0700'
    owner: postgres
    path: '{{ item }}'
    state: directory
  loop:
    # - /etc/postgresql
    - /var/lib/postgresql
    # - /var/log/postgresql

- name: Extract PostgreSQL binaries
  ansible.builtin.unarchive:
    dest: /usr/local
    group: root
    owner: root
    src: postgresql.tar.gz
