- name: Create a PostgreSQL user
  ansible.builtin.user:
    comment: PostgreSQL user
    name: postgres
    shell: /bin/bash

- name: Create PostgreSQL config, data and log directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/postgresql
    - /var/lib/postgresql
    - /var/log/postgresql

- name: Change an ownership of PostgreSQL directories
  ansible.builtin.file:
    group: postgres
    owner: postgres
    path: '{{ item }}'
    state: directory
  loop:
    - /var/lib/postgresql
    - /var/log/postgresql

- name: Extract PostgreSQL binaries and config files
  ansible.builtin.unarchive:
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
  loop:
    - { dest: '/usr/local', src: 'postgresql.tar.gz' }
    - { dest: '/etc/postgresql', src: 'postgresql-conf.tar.gz' }
