- name: Configure Patroni logs rotation
  ansible.builtin.blockinfile:
    block: |
      /var/log/patroni/patroni.log {
        rotate 7
        daily
        compress
        delaycompress
        missingok
        notifempty
        create 0600 postgres postgres
        su postgres postgres
      }
    create: true
    path: /etc/logrotate.d/patroni
