- name: Load Watchdog
  community.general.modprobe:
    name: softdog
    persistent: present
    state: present

- name: Change ownership to postgres
  ansible.builtin.file:
    group: postgres
    # mode: '0600'
    owner: postgres
    path: /dev/watchdog

- name: Make ownership continual
  ansible.builtin.lineinfile:
    create: true
    line: GROUP="postgres", KERNEL=="watchdog", OWNER="postgres"
    path: /etc/udev/rules.d/99-watchdog.rules
