---

- name: Apply a bunch of kernel parameters
  ansible.posix.sysctl:
    ignoreerrors: false
    name: '{{ item.name }}'
    reload: true
    state: present
    sysctl_file: /etc/sysctl.d/30-postgresql.conf
    sysctl_set: false
    value: '{{ item.value }}'
  loop:
    - { name: 'kernel.sched_autogroup_enabled', value: '0' }
    - { name: 'kernel.sched_migration_cost_ns', value: '5000000' }
    - { name: 'vm.dirty_background_bytes', value: '67108864' }
    - { name: 'vm.dirty_bytes', value: '1073741824' }
    - { name: 'vm.swappiness', value: '1' }
    - { name: 'vm.zone_reclaim_mode', value: '0' }

...
