- name: Copy pgbouncer archive to a host
  ansible.builtin.copy:
    src: pgbouncer.tar.gz
    dest: /tmp

- name: Extract an archive
  ansible.builtin.unarchive:
    src: /tmp/pgbouncer.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy PgBouncer binary and libraries to respective directories
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    remote_src: yes
  loop:
    - { src: '/tmp/pgbouncer', dest: '/usr/local/bin' }
    - { src: '/tmp/libcares.so.2', dest: '/usr/lib/x86_64-linux-gnu' }
    - { src: '/tmp/libevent-2.1.so.7', dest: '/usr/lib/x86_64-linux-gnu' }

- name: Change a PgBouncer binary's mode
  ansible.builtin.file:
    path: /usr/local/bin/pgbouncer
    mode: '0755' 

- name: Create PgBouncer config, log and pid-file directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/pgbouncer
    - /var/log/pgbouncer
    - /var/run/pgbouncer

- name: Change an ownership of PgBouncer directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: postgres
    group: postgres
  loop:
    - /var/log/pgbouncer
    - /var/run/pgbouncer

- name: Copy PgBouncer config and systemd unit files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'pgbouncer.ini', dest: '/etc/pgbouncer' }
    - { src: 'userlist.txt', dest: '/etc/pgbouncer' }
    - { src: 'pgbouncer.service', dest: '/etc/systemd/system' }

- name: Reread systemd configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable PgBouncer
  ansible.builtin.systemd:
    name: pgbouncer
    state: started
    enabled: true
    masked: no