- name: Tune PostgreSQL
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_set:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    connect_params:
      host: /tmp
  loop:
    - { name: 'checkpoint_completion_target', value: '0.9' }
    - { name: 'default_statistics_target', value: '100' }
    - { name: 'effective_cache_size', value: '1536MB' }
    - { name: 'effective_io_concurrency', value: '200' }
    - { name: 'huge_pages', value: 'off' }
    - { name: 'maintenance_work_mem', value: '128MB' }
    - { name: 'max_connections', value: '200' }
    - { name: 'max_parallel_workers', value: '1' }
    - { name: 'max_wal_size', value: '4GB' }
    - { name: 'min_wal_size', value: '1GB' }
    - { name: 'random_page_cost', value: '1.1' }
    - { name: 'shared_buffers', value: '512MB' }
    - { name: 'wal_buffers', value: '16MB' }
    - { name: 'work_mem', value: '2621.44kB' }

- name: Restart PostgreSQL
  ansible.builtin.systemd_service:
    name: postgresql
    state: restarted
