# - name: Render Patroni config
#   ansible.builtin.template:
#     dest: /etc/patroni.yml
#     src: patroni.yml.j2

# - name: Create Patroni log directory and file
#   ansible.builtin.file:
#     group: postgres
#     mode: '{{ item.mode }}'
#     owner: postgres
#     path: '{{ item.path }}'
#     state: '{{ item.state }}'
#   loop:
#     - { mode: '0700', path: '/var/log/patroni', state: 'directory' }
#     - { access_time: preserve, mode: '0600', modification_time: preserve,
#         path: '/var/log/patroni/patroni.log', state: 'touch' }

- name: Extract Patroni
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    group: root
    owner: root
    src: patroni.tar.gz

- name: Render Patroni config
  ansible.builtin.template:
    dest: /etc/patroni.yml
    src: patroni.yml.j2
  notify:
    - Restart Patroni

- name: Create Patroni log directory
  ansible.builtin.file:
    group: postgres
    mode: '0700'
    owner: postgres
    path: /var/log/patroni
    state: directory

- name: Copy Patroni systemd unit file
  ansible.builtin.copy:
    dest: /etc/systemd/system
    src: patroni.service

- name: Reread systemd configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start and enable Patroni
  ansible.builtin.systemd_service:
    enabled: true
    masked: false
    name: patroni
    state: started
